//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use super::sea_orm_active_enums::Store;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "od_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub name: String,
    pub store: Store,
    pub source_url: String,
    pub cid: Option<String>,
    pub car_url: Option<String>,
    pub piece_id: Option<String>,
    pub data_size: Option<u64>,
    pub generate_car_worker: Option<String>,
    pub retry: i32,
    pub created: i64,
    pub updated: i64,
    pub deleted: i64,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
