//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "od_miner_configs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub miner_id: String,
    pub miner_price: String,
    pub duration: u64,
    pub miner_api_info: String,
    pub market_path: String,
    pub deleted: i32,
    pub memo: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
