//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "od_trades")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub file_id: u32,
    pub proposal_cid: Option<String>,
    pub deal_id: Option<String>,
    pub status: Option<String>,
    pub from_wallet: String,
    pub miner_id: String,
    pub retry: i32,
    pub created: i64,
    pub updated: i64,
    pub deleted: i64,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
